services:
  airflow:
    build:
      context: .
      dockerfile: Containerfile
      args:
        AIRFLOW_VERSION: "3.2.0"
    container_name: goldprice-airflow
    env_file:
      - .env
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: /opt/airflow/config/simple_auth_manager_passwords.json
      GOLD_SQL_DIR: /opt/airflow/sql
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./sql:/opt/airflow/sql
    command: standalone
